//! Integration test for Parquet I/O functionality.
//!
//! This test demonstrates reading and writing embeddings in Parquet format
//! with proper ELID generation integration.

use anyhow::Result;
use elid_cli::io::parquet::{read_parquet, write_parquet};
use std::fs;
use std::path::PathBuf;

fn get_test_file_path(name: &str) -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("target");
    // Ensure directory exists
    fs::create_dir_all(&path).expect("Failed to create target directory");
    path.push(name);
    path
}

#[test]
fn test_parquet_write_and_read_integration() -> Result<()> {
    let test_file = get_test_file_path("test_write_read.parquet");

    // Sample embeddings (simulating real embeddings from a model)
    let embeddings = vec![
        vec![0.123, 0.456, 0.789, 0.012],
        vec![0.234, 0.567, 0.890, 0.123],
        vec![0.345, 0.678, 0.901, 0.234],
        vec![0.456, 0.789, 0.012, 0.345],
        vec![0.567, 0.890, 0.123, 0.456],
    ];

    // Simulated ELIDs (in practice these would be generated by elid-core)
    let elids = vec![
        "M10_A1B2C3D4".to_string(),
        "M10_E5F6G7H8".to_string(),
        "M10_I9J0K1L2".to_string(),
        "M10_M3N4O5P6".to_string(),
        "M10_Q7R8S9T0".to_string(),
    ];

    // Write to Parquet
    write_parquet(
        test_file.to_str().unwrap(),
        &embeddings,
        &elids,
        "embedding_vector",
    )?;

    // Verify file exists
    assert!(test_file.exists(), "Parquet file should be created");

    // Read back
    let read_embeddings = read_parquet(test_file.to_str().unwrap(), "embedding_vector")?;

    // Verify count
    assert_eq!(
        read_embeddings.len(),
        embeddings.len(),
        "Should read same number of embeddings"
    );

    // Verify values (with floating point tolerance)
    for (i, (original, read)) in embeddings.iter().zip(read_embeddings.iter()).enumerate() {
        assert_eq!(
            original.len(),
            read.len(),
            "Embedding {} should have same dimension",
            i
        );

        for (j, (o, r)) in original.iter().zip(read.iter()).enumerate() {
            assert!(
                (o - r).abs() < 1e-6,
                "Embedding {}, value {} mismatch: {} vs {}",
                i,
                j,
                o,
                r
            );
        }
    }

    // Cleanup
    fs::remove_file(test_file)?;

    Ok(())
}

#[test]
fn test_parquet_with_large_embeddings() -> Result<()> {
    let test_file = get_test_file_path("test_large.parquet");

    // Simulate large embeddings (e.g., from text-embedding-3-large: 3072 dimensions)
    let dimension: usize = 1024;
    let count: usize = 100;

    let embeddings: Vec<Vec<f32>> = (0..count)
        .map(|i| {
            (0..dimension)
                .map(|j| ((i * dimension + j) as f32) * 0.001)
                .collect()
        })
        .collect();

    let elids: Vec<String> = (0..count).map(|i| format!("ELID_{:04}", i)).collect();

    // Write
    write_parquet(
        test_file.to_str().unwrap(),
        &embeddings,
        &elids,
        "large_embedding",
    )?;

    // Verify file size is reasonable
    let metadata = fs::metadata(&test_file)?;
    let file_size_kb = metadata.len() / 1024;
    let raw_size_kb = ((count * dimension * 4) / 1024) as u64; // 4 bytes per f32

    println!(
        "File size: {} KB for {} embeddings of {} dimensions (raw would be {} KB)",
        file_size_kb, count, dimension, raw_size_kb
    );

    // File size should be reasonable (with metadata overhead, compression may not always reduce size
    // for highly structured sequential data, but it should not be excessively large)
    assert!(
        file_size_kb < raw_size_kb * 2,
        "Parquet file should not be excessively larger than raw data"
    );

    // Read back and verify a sample
    let read_embeddings = read_parquet(test_file.to_str().unwrap(), "large_embedding")?;
    assert_eq!(read_embeddings.len(), count);
    assert_eq!(read_embeddings[0].len(), dimension);

    // Cleanup
    fs::remove_file(test_file)?;

    Ok(())
}

#[test]
fn test_parquet_error_handling() {
    // Test reading non-existent file
    let result = read_parquet("/nonexistent/file.parquet", "embedding");
    assert!(result.is_err());

    // Test reading wrong column
    let test_file = get_test_file_path("test_error.parquet");
    let embeddings = vec![vec![0.1, 0.2]];
    let elids = vec!["ELID_001".to_string()];

    write_parquet(
        test_file.to_str().unwrap(),
        &embeddings,
        &elids,
        "correct_column",
    )
    .unwrap();

    let result = read_parquet(test_file.to_str().unwrap(), "wrong_column");
    assert!(result.is_err());

    // Cleanup
    fs::remove_file(test_file).ok();
}
