/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** ELID encoding profile */
export const enum ElidProfile {
  /** 128-bit SimHash (29 characters) - Best for similarity search */
  Mini128 = 0,
  /** 10D Morton curve (16-24 characters) - Fast indexing */
  Morton10x10 = 1,
  /** 10D Hilbert curve (16-24 characters) - Maximum locality */
  Hilbert10x10 = 2
}
/**
 * Encode a high-dimensional embedding to a sortable string identifier.
 *
 * # Arguments
 *
 * * `embedding` - Float64Array of length 64-2048
 * * `profile` - Encoding profile (Mini128, Morton10x10, or Hilbert10x10)
 *
 * # Returns
 *
 * Sortable string identifier (29 chars for Mini128, 16-24 for others)
 *
 * # Errors
 *
 * Throws if embedding dimensions are invalid or encoding fails
 *
 * # Example
 *
 * ```javascript
 * const { encodeElid, ElidProfile } = require('elid');
 *
 * const embedding = new Float64Array(768).fill(0.5);
 * const elidId = encodeElid(embedding, ElidProfile.Mini128);
 * console.log(elidId); // 29-character string
 * ```
 */
export declare function encodeElid(embedding: Float64Array, profile: ElidProfile): string
/**
 * Decode an ELID string back to raw bytes.
 *
 * # Arguments
 *
 * * `elid` - ELID string identifier (base32hex encoded)
 *
 * # Returns
 *
 * Buffer containing raw bytes including 2-byte header (18 bytes for Mini128; 15 bytes for Morton/Hilbert10x10)
 *
 * # Errors
 *
 * Throws if ELID string is malformed or invalid encoding
 *
 * # Example
 *
 * ```javascript
 * const { decodeElid } = require('elid');
 *
 * const bytes = decodeElid('0123456789ABCDEFGHIJKLMNOPQ');
 * console.log(bytes.length); // 18 (2 header + 16 payload for Mini128)
 * ```
 */
export declare function decodeElid(elid: string): Buffer
/**
 * Calculate Hamming distance between two ELIDs.
 *
 * # Arguments
 *
 * * `elid1` - First ELID string
 * * `elid2` - Second ELID string (must use same profile as elid1)
 *
 * # Returns
 *
 * Hamming distance (0-128 for Mini128, 0-80 for Morton/Hilbert10x10).
 * Lower distance indicates higher similarity.
 *
 * # Errors
 *
 * Throws if ELIDs use different profiles or are malformed
 *
 * # Example
 *
 * ```javascript
 * const { encodeElid, hammingDistanceElid, ElidProfile } = require('elid');
 *
 * const embedding = new Float64Array(768).fill(1.0);
 * const elid1 = encodeElid(embedding, ElidProfile.Mini128);
 * const elid2 = encodeElid(embedding, ElidProfile.Mini128);
 * const distance = hammingDistanceElid(elid1, elid2);
 * console.log(distance); // 0 (identical embeddings)
 * ```
 */
export declare function hammingDistanceElid(elid1: string, elid2: string): number
/**
 * Encode multiple embeddings asynchronously using Tokio for non-blocking execution.
 *
 * # Arguments
 *
 * * `embeddings` - Array of Float64Array, each length 64-2048
 * * `profile` - Encoding profile for all embeddings
 *
 * # Returns
 *
 * Promise resolving to array of ELID strings, same order as input
 *
 * # Errors
 *
 * Throws if any embedding has invalid dimensions
 *
 * # Example
 *
 * ```javascript
 * const { encodeBatch, ElidProfile } = require('elid');
 *
 * const embeddings = Array.from({ length: 1000 }, () =>
 *   new Float64Array(768).fill(Math.random())
 * );
 * const elids = await encodeBatch(embeddings, ElidProfile.Mini128);
 * console.log(elids.length); // 1000
 * ```
 */
export declare function encodeBatch(embeddings: Array<Float64Array>, profile: ElidProfile): Promise<Array<string>>
