# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'


module ElidFfi
  def self.uniffi_in_range(i, type_name, min, max)
  raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)
  i = i.to_int
  raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless (min <= i && i < max)
  i
end

def self.uniffi_utf8(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v = v.to_str.encode(Encoding::UTF_8)
  raise Encoding::InvalidByteSequenceError, "not a valid UTF-8 encoded string" unless v.valid_encoding?
  v
end

def self.uniffi_bytes(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v.to_str
end

  class RustBuffer < FFI::Struct
  layout :capacity, :int32,
         :len,      :int32,
         :data,     :pointer

  def self.alloc(size)
    return ElidFfi.rust_call(:ffi_elid_ffi_rustbuffer_alloc, size)
  end

  def self.reserve(rbuf, additional)
    return ElidFfi.rust_call(:ffi_elid_ffi_rustbuffer_reserve, rbuf, additional)
  end

  def free
    ElidFfi.rust_call(:ffi_elid_ffi_rustbuffer_free, self)
  end

  def capacity
    self[:capacity]
  end

  def len
    self[:len]
  end

  def len=(value)
    self[:len] = value
  end

  def data
    self[:data]
  end

  def to_s
    "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
  end

  # The allocated buffer will be automatically freed if an error occurs, ensuring that
  # we don't accidentally leak it.
  def self.allocWithBuilder
    builder = RustBufferBuilder.new

    begin
      yield builder
    rescue => e
      builder.discard
      raise e
    end
  end

  # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
  # leak it even if an error occurs.
  def consumeWithStream
    stream = RustBufferStream.new self

    yield stream

    raise RuntimeError, 'junk data left in buffer after consuming' if stream.remaining != 0
  ensure
    free
  end# The primitive String type.

  def self.allocFromString(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write value.encode('utf-8')
      return builder.finalize
    end
  end

  def consumeIntoString
    consumeWithStream do |stream|
      return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
    end
  end

  

  # The Enum type UniProfile.

  def self.check_lower_TypeUniProfile(v)
  end

  def self.alloc_from_TypeUniProfile(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniProfile(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniProfile
    consumeWithStream do |stream|
      return stream.readTypeUniProfile
    end
  end
  

  # The Sequence<T> type for u8.

  def self.check_lower_Sequenceu8(v)
    v.each do |item|
      
    end
  end

  def self.alloc_from_Sequenceu8(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Sequenceu8(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceu8
    consumeWithStream do |stream|
      return stream.readSequenceu8
    end
  end

  # The Sequence<T> type for f32.

  def self.check_lower_Sequencef32(v)
    v.each do |item|
      
    end
  end

  def self.alloc_from_Sequencef32(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Sequencef32(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequencef32
    consumeWithStream do |stream|
      return stream.readSequencef32
    end
  end

  # The Sequence<T> type for string.

  def self.check_lower_Sequencestring(v)
    v.each do |item|
      
    end
  end

  def self.alloc_from_Sequencestring(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Sequencestring(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequencestring
    consumeWithStream do |stream|
      return stream.readSequencestring
    end
  end

  # The Sequence<T> type for Sequencef32.

  def self.check_lower_SequenceSequencef32(v)
    v.each do |item|
      RustBuffer.check_lower_Sequencef32(item)
    end
  end

  def self.alloc_from_SequenceSequencef32(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceSequencef32(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceSequencef32
    consumeWithStream do |stream|
      return stream.readSequenceSequencef32
    end
  end

  
end

module UniFFILib
  class ForeignBytes < FFI::Struct
    layout :len,      :int32,
           :data,     :pointer

    def len
      self[:len]
    end

    def data
      self[:data]
    end

    def to_s
      "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
    end
  end
end

private_constant :UniFFILib
  
# Helper for structured reading of values from a RustBuffer.
class RustBufferStream

  def initialize(rbuf)
    @rbuf = rbuf
    @offset = 0
  end

  def remaining
    @rbuf.len - @offset
  end

  def read(size)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    data = @rbuf.data.get_bytes @offset, size

    @offset += size

    data
  end

  def readU8
    unpack_from 1, 'c'
  end

  def readU32
    unpack_from 4, 'L>'
  end

  def readF32
    unpack_from 4, 'g'
  end

  def readString
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative string length' if size.negative?

    read(size).force_encoding(Encoding::UTF_8)
  end

  

  

  # The Error type UniElidError

  def readTypeUniElidError
    variant = unpack_from 4, 'l>'
    
    if variant == 1
      return UniElidError::InvalidDimension.new(
        readString()
      )
    end
    if variant == 2
      return UniElidError::InvalidValue.new(
        readString()
      )
    end
    if variant == 3
      return UniElidError::InvalidEncoding.new(
        readString()
      )
    end
    if variant == 4
      return UniElidError::InvalidHeader.new(
        readString()
      )
    end
    if variant == 5
      return UniElidError::ProfileMismatch.new(
        readString()
      )
    end
    if variant == 6
      return UniElidError::TransformNotFound.new(
        readString()
      )
    end

    raise InternalError, 'Unexpected variant tag for TypeUniElidError'
  end
  

  
  
  # The Enum type UniProfile.

  def readTypeUniProfile
    variant = unpack_from 4, 'l>'
    
    if variant == 1
      return UniProfile::MINI128
    end
    if variant == 2
      return UniProfile::MORTON10X10
    end
    if variant == 3
      return UniProfile::HILBERT10X10
    end

    raise InternalError, 'Unexpected variant tag for TypeUniProfile'
  end

  

  # The Sequence<T> type for u8.

  def readSequenceu8
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readU8
    end

    items
  end

  # The Sequence<T> type for f32.

  def readSequencef32
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readF32
    end

    items
  end

  # The Sequence<T> type for string.

  def readSequencestring
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readString
    end

    items
  end

  # The Sequence<T> type for Sequencef32.

  def readSequenceSequencef32
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readSequencef32
    end

    items
  end

  

  def unpack_from(size, format)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    value = @rbuf.data.get_bytes(@offset, size).unpack format

    @offset += size

    # TODO: verify this
    raise 'more than one element!!!' if value.size > 1

    value[0]
  end
end

private_constant :RustBufferStream
  
# Helper for structured writing of values into a RustBuffer.
class RustBufferBuilder
  def initialize
    @rust_buf = RustBuffer.alloc 16
    @rust_buf.len = 0
  end

  def finalize
    rbuf = @rust_buf

    @rust_buf = nil

    rbuf
  end

  def discard
    return if @rust_buf.nil?

    rbuf = finalize
    rbuf.free
  end

  def write(value)
    reserve(value.bytes.size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
    end
  end

  def write_U8(v)
    v = ElidFfi::uniffi_in_range(v, "u8", 0, 2**8)
    pack_into(1, 'c', v)
  end

  def write_U32(v)
    v = ElidFfi::uniffi_in_range(v, "u32", 0, 2**32)
    pack_into(4, 'L>', v)
  end

  def write_F32(v)
    pack_into(4, 'g', v)
  end

  def write_String(v)
    v = ElidFfi::uniffi_utf8(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  

  # The Enum type UniProfile.

  def write_TypeUniProfile(v)
    pack_into(4, 'l>', v)
 end
   

  # The Sequence<T> type for u8.

  def write_Sequenceu8(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_U8(item)
    end
  end

  # The Sequence<T> type for f32.

  def write_Sequencef32(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_F32(item)
    end
  end

  # The Sequence<T> type for string.

  def write_Sequencestring(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_String(item)
    end
  end

  # The Sequence<T> type for Sequencef32.

  def write_SequenceSequencef32(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_Sequencef32(item)
    end
  end

  

  private

  def reserve(num_bytes)
    if @rust_buf.len + num_bytes > @rust_buf.capacity
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes)
    end

    yield

    @rust_buf.len += num_bytes
  end

  def pack_into(size, format, value)
    reserve(size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
    end
  end
end

private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
  layout :code,    :int8,
         :error_buf, RustBuffer

  def code
    self[:code]
  end

  def error_buf
    self[:error_buf]
  end

  def to_s
    "RustCallStatus(code=#{self[:code]})"
  end
end

# These match the values from the uniffi::rustcalls module
CALL_SUCCESS = 0
CALL_ERROR = 1
CALL_PANIC = 2


class UniElidError
    InvalidDimension = Class.new StandardError
    InvalidValue = Class.new StandardError
    InvalidEncoding = Class.new StandardError
    InvalidHeader = Class.new StandardError
    ProfileMismatch = Class.new StandardError
    TransformNotFound = Class.new StandardError

end



# Map error modules to the RustBuffer method name that reads them
ERROR_MODULE_TO_READER_METHOD = {

  UniElidError => :readTypeUniElidError,


}

private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                 :RustCallStatus

def self.consume_buffer_into_error(error_module, rust_buffer)
  rust_buffer.consumeWithStream do |stream|
    reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
    return stream.send(reader_method)
  end
end

class InternalError < StandardError
end

def self.rust_call(fn_name, *args)
  # Call a rust function
  rust_call_with_error(nil, fn_name, *args)
end

def self.rust_call_with_error(error_module, fn_name, *args)
  # Call a rust function and handle errors
  #
  # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.


  # Note: RustCallStatus.new zeroes out the struct, which is exactly what we
  # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
  # data=NULL))
  status = RustCallStatus.new
  args << status

  result = UniFFILib.public_send(fn_name, *args)

  case status.code
  when CALL_SUCCESS
    result
  when CALL_ERROR
    if error_module.nil?
      status.error_buf.free
      raise InternalError, "CALL_ERROR with no error_module set"
    else
      raise consume_buffer_into_error(error_module, status.error_buf)
    end
  when CALL_PANIC
    # When the rust code sees a panic, it tries to construct a RustBuffer
    # with the message.  But if that code panics, then it just sends back
    # an empty buffer.
    if status.error_buf.len > 0
      raise InternalError, status.error_buf.consumeIntoString()
    else
      raise InternalError, "Rust panic"
    end
  else
    raise InternalError, "Unknown call status: #{status.code}"
  end
end

private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
# For now we just look it up by name.
module UniFFILib
  extend FFI::Library

  
  # Load native library from gem directory
  lib_dir = File.expand_path('..', __FILE__)
  lib_name = FFI::Platform.windows? ? 'elid_ffi.dll' :
             FFI::Platform.mac? ? 'libelid_ffi.dylib' :
             'libelid_ffi.so'
  lib_path = File.join(lib_dir, lib_name)

  if File.exist?(lib_path)
    ffi_lib lib_path
  else
    # Fallback to system library search
    ffi_lib 'elid_ffi'
  end
  

  attach_function :uniffi_elid_ffi_fn_func_uni_decode,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_elid_ffi_fn_func_uni_encode,
    [RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_elid_ffi_fn_func_uni_encode_batch,
    [RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_elid_ffi_fn_func_uni_hamming_distance,
    [RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    :uint32
  attach_function :ffi_elid_ffi_rustbuffer_alloc,
    [:int32, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_elid_ffi_rustbuffer_from_bytes,
    [ForeignBytes, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_elid_ffi_rustbuffer_free,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  attach_function :ffi_elid_ffi_rustbuffer_reserve,
    [RustBuffer.by_value, :int32, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_elid_ffi_checksum_func_uni_decode,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_elid_ffi_checksum_func_uni_encode,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_elid_ffi_checksum_func_uni_encode_batch,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_elid_ffi_checksum_func_uni_hamming_distance,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :ffi_elid_ffi_uniffi_contract_version,
    [RustCallStatus.by_ref],
    :uint32
  
end

  # Public interface members begin here.

  
  
  
  

class UniProfile
  MINI128 = 1
  MORTON10X10 = 2
  HILBERT10X10 = 3
  
end


  

  
  

def self.uni_decode(elid)
    elid = ElidFfi::uniffi_utf8(elid)
    
    
  result = ElidFfi.rust_call_with_error(UniElidError,:uniffi_elid_ffi_fn_func_uni_decode,RustBuffer.allocFromString(elid))
  return result.consumeIntoSequenceu8
end


  
  

def self.uni_encode(embedding, profile)
    embedding = embedding
    RustBuffer.check_lower_Sequencef32(embedding)
    
    profile = profile
    RustBuffer.check_lower_TypeUniProfile(profile)
    
  result = ElidFfi.rust_call_with_error(UniElidError,:uniffi_elid_ffi_fn_func_uni_encode,RustBuffer.alloc_from_Sequencef32(embedding),RustBuffer.alloc_from_TypeUniProfile(profile))
  return result.consumeIntoString
end


  
  

def self.uni_encode_batch(embeddings, profile)
    embeddings = embeddings
    RustBuffer.check_lower_SequenceSequencef32(embeddings)
    
    profile = profile
    RustBuffer.check_lower_TypeUniProfile(profile)
    
  result = ElidFfi.rust_call_with_error(UniElidError,:uniffi_elid_ffi_fn_func_uni_encode_batch,RustBuffer.alloc_from_SequenceSequencef32(embeddings),RustBuffer.alloc_from_TypeUniProfile(profile))
  return result.consumeIntoSequencestring
end


  
  

def self.uni_hamming_distance(elid1, elid2)
    elid1 = ElidFfi::uniffi_utf8(elid1)
    
    
    elid2 = ElidFfi::uniffi_utf8(elid2)
    
    
  result = ElidFfi.rust_call_with_error(UniElidError,:uniffi_elid_ffi_fn_func_uni_hamming_distance,RustBuffer.allocFromString(elid1),RustBuffer.allocFromString(elid2))
  return result.to_i
end


  

  
end

